eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
